### ISSUE TITLE
Settings page missing?

### ISSUE THREAD

**Issue by dvision1979** [xJMV/PrepInventory#51]
settings.php is non existent. Is it missing from the release or has it not been implemented yet?

**Comment by VA2XJM** [comment]
It do not yet exists. It is planned to allows users to change their password and personal settings when users will be stored into the database instead of the config file.

I only work on the project when I have spare time, but as winter is here, I will soon re-start working on the project.

**Comment by dvision1979** [comment]
I would contribute as I am skilled enough with the web development, although I don’t know actually how to work with github.
Altogether, it is good news to know that you did not drop the project.

Regards, 
Dan

**Comment by xJMV** [comment]
ca24562a2eb0bdd8666770619b285dd3885cfff3

**Comment by VA2XJM** [comment]
Fixed for next release!
